<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!--                                                                                       -->
    <!-- macros for making track                                                               -->
    <!--     * useful when difining entities for ContinuousTrack plugin                        -->
    <!--     * see gazebo_continuous_track_example/urdf/example_track.urdf.xacro to know usage -->
    <!--                                                                                       -->

    <xacro:include filename="macros_common_gazebo.urdf.xacro" />

    <!-- trajectory segment templates which can be used with common population macros -->

    <xacro:macro name="make_straight_segment_link_template" params="mass:=^ size_x:=^ size_y:=^ size_z:=^">
        <xacro:make_box_inertial pose="${size_x / 2} 0 0 0 0 0" />
    </xacro:macro>

    <xacro:macro name="make_straight_segment_joint_template" params="parent:=^ implicit_spring_damper:=^|1">
        <parent>${parent}</parent>
        <axis>
            <xyz>1 0 0</xyz>
            <use_parent_model_frame>0</use_parent_model_frame>
        </axis>
        <physics>
            <ode>
                <implicit_spring_damper>${implicit_spring_damper}</implicit_spring_damper>
            </ode>
        </physics>
    </xacro:macro>

    <xacro:macro name="make_arc_segment_link_template" params="mass:=^ length:=^ radius:=^">
        <xacro:make_cylinder_inertial pose="0 0 ${-radius} ${pi / 2} 0 0" />
    </xacro:macro>

    <xacro:macro name="make_arc_segment_joint_template" params="parent:=^ radius:=^ implicit_spring_damper:=^|1">
        <parent>${parent}</parent>
        <pose>0 0 ${-radius} 0 0 0</pose>
        <axis>
            <xyz>0 1 0</xyz>
            <use_parent_model_frame>0</use_parent_model_frame>
        </axis>
        <physics>
            <ode>
                <implicit_spring_damper>${implicit_spring_damper}</implicit_spring_damper>
            </ode>
        </physics>
    </xacro:macro>

    <!-- macros for populating trajectory segments with common population macros and above templates -->

    <xacro:macro name="populate_straight_segments" params="name_prefix:=^ x:=^|0 y:=^|0 z:=^|0 roll:=^|0 pitch:=^|0 yaw:=^|0 dx:=^|0 dy:=^|0 dz:=^|0 droll:=^|0 dpitch:=^|0 dyaw:=^|0 mass:=^ size_x:=^ size_y:=^ size_z:=^ parent:=^ implicit_spring_damper:=^|1 count:=^">
        <xacro:populate_links name_prefix="${name_prefix}_link">
            <template>
                <xacro:make_straight_segment_link_template />
            </template>
        </xacro:populate_links>
        <xacro:populate_joints name_prefix="${name_prefix}_joint" type="prismatic" child_prefix="${name_prefix}_link">
            <template>
                <xacro:make_straight_segment_joint_template />
            </template>
        </xacro:populate_joints>
    </xacro:macro>

    <xacro:macro name="populate_arc_segments" params="name_prefix:=^ x:=^|0 y:=^|0 z:=^|0 roll:=^|0 pitch:=^|0 yaw:=^|0 dx:=^|0 dy:=^|0 dz:=^|0 droll:=^|0 dpitch:=^|0 dyaw:=^|0 mass:=^ length:=^ radius:=^ parent:=^ implicit_spring_damper:=^|1 count:=^">
        <xacro:populate_links name_prefix="${name_prefix}_link">
            <template>
                <xacro:make_arc_segment_link_template />
            </template>
        </xacro:populate_links>
        <xacro:populate_joints name_prefix="${name_prefix}_joint" type="revolute" child_prefix="${name_prefix}_link">
            <template>
                <xacro:make_arc_segment_joint_template />
            </template>
        </xacro:populate_joints>
    </xacro:macro>

    <!-- macro which expands to plugin definition -->

    <xacro:macro name="make_track_plugin" params="name sprocket_joint:=^ pitch_diameter:=^ length:=^ *pattern">
        <gazebo>
            <plugin name="${name}" filename="libContinuousTrack.so">
                <sprocket>
                    <joint>${sprocket_joint}</joint>
                    <pitch_diameter>${pitch_diameter}</pitch_diameter>
                </sprocket>
                <trajectory>
                    <segment>
                        <joint>${name}_straight_segment_joint0</joint>
                        <end_position>${length}</end_position>
                    </segment>
                    <segment>
                        <joint>${name}_arc_segment_joint0</joint>
                        <end_position>${pi}</end_position>
                    </segment>
                    <segment>
                        <joint>${name}_straight_segment_joint1</joint>
                        <end_position>${length}</end_position>
                    </segment>
                    <segment>
                        <joint>${name}_arc_segment_joint1</joint>
                        <end_position>${pi}</end_position>
                    </segment>
                </trajectory>
                <xacro:insert_block name="pattern" />
            </plugin>
        </gazebo>
    </xacro:macro>

    <!-- main entry point: macro for making oval track by ContinuousTrack plugin -->

    <xacro:macro name="make_track" params="name x:=^|0 y:=^|0 z:=^|0 roll:=^|0 pitch:=^|0 yaw:=^|0 mass:=^ length:=^ radius:=^ width:=^ parent:=^ sprocket_joint:=^ pitch_diameter:=^ *pattern implicit_spring_damper:=^|1">
        <xacro:populate_straight_segments name_prefix="${name}_straight_segment" x="${x - length / 2}" z="${z + radius}" dx="${length}" dz="${-2 * radius}" dpitch="${pi}" mass="${mass / 4}" size_x="${length}" size_y="${width}" size_z="${radius}" count="2" />
        <xacro:populate_arc_segments name_prefix="${name}_arc_segment" x="${x + length / 2}" z="${z + radius}" dx="${-length}" dz="${-2 * radius}" dpitch="${pi}" mass="${mass / 4}" length="${width}" count="2" />
        <xacro:make_track_plugin name="${name}">
            <xacro:insert_block name="pattern" />
        </xacro:make_track_plugin>
    </xacro:macro>

    <!-- macro which expands to box collision and visual. convenient when defining <pattern> in above macro -->

    <xacro:macro name="make_box_element" params="pose:=^|'0 0 0 0 0 0' size:=^ mu:=^|0.5 min_depth:=^|0.01 *material">
        <xacro:make_box_collision />
        <xacro:make_box_visual>
            <xacro:insert_block name="material" />
        </xacro:make_box_visual>
    </xacro:macro>

</robot>